### ISSUE TITLE
Are the generator `values` used only for illustration purpose?

### ISSUE THREAD

**Issue by RoyLING** [mvolkmann/todo-es6#5]
When walking through the whole code, I found the generator `values` is actually not necessary in _todolist.js_ when using with _for-of_ loops:
```javascript
  archiveCompleted() {
    // Not saving completed todos in this version.
    for (let todo of values(this.todos)) {
      if (todo.done) this.delete(todo);
    }
  }
```
In fact, it works with just _for-of_ loops:
```javascript
for (let todo of this.todos) {
...
}
```
please correct me if I am wrong.

**Comment by mvolkmann** [comment]
Sorry, I just saw this. You are correct. I only included generators.js to demonstrate that generators are supported by Traceur. They aren't used by the todo app.
